CREATE TABLE temp
SELECT
	CLIENTS.NAME,
	RECORDS.ACC_REF,
	ACCOUNTS.SALDO,
	SUM(IF(DT = 0, RECORDS.SUM, RECORDS.SUM * (-1))) AS CALCULATED_SALDO
FROM 
	RECORDS
INNER JOIN 
	ACCOUNTS ON RECORDS.ACC_REF = ACCOUNTS.CLIENT_REF
INNER JOIN 
	CLIENTS ON ACCOUNTS.CLIENT_REF = CLIENTS.ID
GROUP BY 
	RECORDS.ACC_REF;
UPDATE ACCOUNTS
INNER JOIN temp ON ACCOUNTS.CLIENT_REF=temp.ACC_REF
SET ACCOUNTS.SALDO=temp.CALCULATED_SALDO
WHERE ACCOUNTS.SALDO != CALCULATED_SALDO;
DROP TABLE temp;


