SELECT
	CLIENTS.NAME,
	RECORDS.ACC_REF,
	ACCOUNTS.SALDO,
	SUM(IF(DT = 0, RECORDS.SUM, RECORDS.SUM * (-1))) AS CALCULATED_SALDO
FROM 
	RECORDS
INNER JOIN 
	ACCOUNTS ON RECORDS.ACC_REF = ACCOUNTS.CLIENT_REF
INNER JOIN 
	CLIENTS ON ACCOUNTS.CLIENT_REF = CLIENTS.ID

GROUP BY 
	RECORDS.ACC_REF
HAVING 
	CALCULATED_SALDO != ACCOUNTS.SALDO;	
